init upload and parse excel file
f-lab-edu/basketball-lab pull request #19
Opened 2024-05-26 04:18 UTC by circuitbreak98

2024-06-03 13:15 UTC, jacob-f-lab commented on app/services/excel_parsing.py
> +        print(new_player_stat)
print 문은 지워주세요 :)

2024-06-03 13:16 UTC, jacob-f-lab requested changes

2024-06-03 13:16 UTC, jacob-f-lab commented on game_record.txt
텍스트 파일들은 혹시 어떤 용도로 레포에 존재하는걸까요?

2024-06-04 02:06 UTC, circuitbreak98 commented on app/services/excel_parsing.py
> +        print(new_player_stat)
지웠습니다.

2024-06-04 02:14 UTC, circuitbreak98 commented on app/services/excel_parsing.py
> +        json.dump(data, data_file, ensure_ascii=False, indent=4)
디버깅 과정에서 추가된 코드인데요. 삭제하는게 나을것 같아 삭제했습니다.

2024-06-04 06:35 UTC, circuitbreak98 commented on game_record.txt
로직 구현할때 참고하려고 만든 파일입니다. 생각해보니 이 파일이 레포에 있을 필요가 없을것 같아 삭제했습니다.

2024-06-04 15:20 UTC, jacob-f-lab approved these changes

2024-06-05 00:34 UTC, merged